export const LABEL = {
    PAGE_HEADING: "World Renewable Energy",
    YEAR: "Year",
    COUNTRIES: "Countries",
    COUNTS: "TeraWatt",
    ENERGY_CONSUMPTION_TERAWATTS: "Energy Consumption in TeraWatt",
    ENERGY_CONSUMPTION_TREND: "Energy Consumption Trend",
    TYPE: "Energy Consumtion by Type",
    ENERGY_CONSUMPTION: "Energy Consumption",
    PARALLEL_COORDINATE_PLOT: "Parallel Coordinate Plot",
    WORLD_MAP_TITLE: "World Renewable Energy Map",
}

export const Constants = {
    WORLD_MAP_SVG_CONTAINER_ID: "WORLD_MAP_SVG_CONTAINER_ID",
    ENERGY_CONSUMPTION_STACKED_AREA_CHART_SVG_CONTAINER_ID: "ENERGY_CONSUMPTION_STACKED_AREA_CHART_SVG_CONTAINER_ID",
    STACKED_BARCHART_TYPE_SVG_CONTAINER_ID: "STACKED_BARCHART_TYPE_SVG_CONTAINER_ID",
    PIE_CHART_SVG_CONTAINER_ID: "PIE_CHART_SVG_CONTAINER_ID",
    PCP_SVG_CONTAINER_ID: "PCP_SVG_CONTAINER_ID",
    DISABLED_COLOR: "#EBEBEF",
    NUMERICAL_FEATUREL: "NUMERICAL_FEATURE",
    CATEGORICAL_FEATURE: "CATEGORICAL_FEATURE",
}